### PR TITLE
Bump cobra to 1.3.0, replace completion command

### PR DESCRIPTION
**Pull request by svix-frank**
The new version of cobra autogenerates a completion command which has the same interface as our custom one, so we can update and drop our command (fewer things to support)! 🎉

### CODE REVIEW

**Review by svix-liam — APPROVED** [review]

**Comment by tasn** [comment]
🎉

**Comment by fcjr** [comment]
This might be minor but I realized the short desc for the generated command starts with a lowercase letter which looks pretty unprofessional given the rest are capital (the help desc is autogenerated with an uppercase so we can't just change to all lowercase).  I made a PR to upstream, gonna hold off on merging this until its released. https://github.com/spf13/cobra/pull/1455

**Comment by svix-frank** [comment]
> This might be minor but I realized the short desc for the generated command starts with a lowercase letter which looks pretty unprofessional given the rest are capitalized. (The help desc is autogenerated with an uppercase so we can't just change to all lowercase). I made a PR to upstream, gonna hold off on merging this until its released. [spf13/cobra#1455](https://github.com/spf13/cobra/pull/1455)

My cobra patch finally got merged, just waiting for them to make another release.

**Comment by tasn** [comment]
🎉

**Review by tasn — APPROVED** [review]

**Pull request merged**
