### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by solo-fish**
### Overview
Update docs

### CODE REVIEW

**Comment by solo-fish** [comment]
MB, meant to target my fork, Ignore.

**Comment by tasn** [comment]
Ignored. Though super excited to have it on snap. Please open a PR once ready. 😍

**Comment by solo-fish** [comment]
@tasn Hey I have a published [version here](https://snapcraft.io/svix-cli) that I used for testing - Do you have a canonical account I can transfer the name/ownership to for svix?

**Comment by tasn** [comment]
@solo-fish, not yet, but we can create one! @svix-frank, can you please take a look?

**Comment by solo-fish** [comment]
@tasn SGTM - I'm raising a PR now.

**Comment by tasn** [comment]
Sweet! Looking forward!

**Comment by solo-fish** [comment]
@tasn cool - there's some nuance around automating the snap build & release process. If you'd like to chat real-time feel free to share a discord/slack. cheers.

**Comment by tasn** [comment]
Come join us at https://svix.com/slack/ and chat with @svix-frank there, he's the one doing the packaging (and the CLI development).

**Pull request closed without merging**
